// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function E下载模型(arg1) {
  return window['go']['main']['App']['E下载模型'](arg1);
}

export function E停止下载() {
  return window['go']['main']['App']['E停止下载']();
}

export function E删除模型(arg1) {
  return window['go']['main']['App']['E删除模型'](arg1);
}

export function E对话(arg1, arg2) {
  return window['go']['main']['App']['E对话'](arg1, arg2);
}

export function E按钮1被点击() {
  return window['go']['main']['App']['E按钮1被点击']();
}

export function E搜索模型(arg1) {
  return window['go']['main']['App']['E搜索模型'](arg1);
}

export function E检查更新() {
  return window['go']['main']['App']['E检查更新']();
}

export function E模型改名(arg1, arg2) {
  return window['go']['main']['App']['E模型改名'](arg1, arg2);
}

export function E获取模型列表() {
  return window['go']['main']['App']['E获取模型列表']();
}

export function E设置服务器地址(arg1) {
  return window['go']['main']['App']['E设置服务器地址'](arg1);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
